### ISSUE TITLE
「やられた」の直後ではなく数秒後（やられた表示が消えるくらいまで）に保存をリクエストできるようにする

### ISSUE THREAD

**Issue by sasagar** [tfandkusu/ikut3#33]
もしかしたら配信者目線かもしれないのですが、「やられた」が出てからすぐに録画をリクエストすると、  
素材としては扱いづらく、もう少しバッファが欲しいという状態でした。  
オプションとして数秒遅延を入れられるような仕組みがあるととても嬉しいなと感じました。

**Comment by tfandkusu** [comment]
@sasagar この度はご意見ありがとうございます。このような形で作成しリリースしました。
https://note.com/tfandkusu/n/nc0d2421c75c0

**Comment by sasagar** [comment]
お忙しい中対応していただきましてありがとうございました！

理想的な形だと思います。
個人的にFlutterも勉強したいのでコード面からも参考にさせて頂けたらと思います。
